---
# tasks file for unattended-upgrades

- name: "packages"
  package:
    name: '{{ item }}'
  with_items:
    - '{{ uu_packages }}'
  tags:
    - unattended-upgrades
    - packages

- name: "auto-upgrade config"
  template:
    src: 'auto-upgrades.j2'
    dest: '{{ uu_auto_upgrade_config }}'
  tags:
    - unattended-upgrades
    - uconfig

- name: "unattended-upgrades config"
  template:
    src: 'unattended-upgrades.j2'
    dest: '{{ uu_unattended_upgrades_config }}'
  tags:
    - unattended-upgrades
    - uuconfig

- name: apt-daily-upgrade timer override dir
  file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory
  when:
    uu_timer_oncalendar is defined or
    uu_timer_randomizeddelaysec is defined or
    uu_timer_persistent is defined
  tags:
    - unattended-upgrades
    - timer

- name: apt-daily-upgrade timer override
  template:
    src: apt-daily-upgrade.timer.override.conf.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
  when:
    uu_timer_oncalendar is defined or
    uu_timer_randomizeddelaysec is defined or
    uu_timer_persistent is defined
  notify:
    - systemd reload
  tags:
    - unattended-upgrades
    - timer

- name: remove apt-daily-upgrade timer override
  file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    state: absent
  when:
    not (
    uu_timer_oncalendar is defined or
    uu_timer_randomizeddelaysec is defined or
    uu_timer_persistent is defined
    )
  notify:
    - systemd reload
  tags:
    - unattended-upgrades
    - timer

- name: remove apt-daily-upgrade timer override dir
  file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: absent
  when:
    not (
    uu_timer_oncalendar is defined or
    uu_timer_randomizeddelaysec is defined or
    uu_timer_persistent is defined
    )
  tags:
    - unattended-upgrades
    - timer
...
