---
# tasks file for unattended-upgrades
- name: Package
  ansible.builtin.package:
    name: '{{ uu_packages }}'
    update_cache: true
  tags:
    - unattended-upgrades
    - package

- name: Dpkg_divert
  community.general.dpkg_divert:
    path: "{{ item.path }}"
    divert: "{{ item.divert }}"
    rename: true
  loop:
    - path: "{{ uu_auto_upgrade_config }}"
      divert: "/etc/apt/20auto-upgrades.distrib"
    - path: "{{ uu_unattended_upgrades_config }}"
      divert: "/etc/apt/50unattended-upgrades.distrib"
  tags:
    - unattended-upgrades
    - dpkg_divert

- name: Ensure obsolete files from previous role versions are absent
  ansible.builtin.file:
    path: "/etc/apt/apt.conf.d/{{ item }}"
    state: absent
  loop:
    - 21auto-upgrades
    - 51unattended-upgrades
  tags:
    - unattended-upgrades
    - obsolete

- name: Auto-upgrade config
  ansible.builtin.template:
    src: auto-upgrades.j2
    dest: '{{ uu_auto_upgrade_config }}'
    mode: 0644
  tags:
    - unattended-upgrades
    - auconfig

- name: Unattended-upgrades config
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: '{{ uu_unattended_upgrades_config }}'
    mode: 0644
  tags:
    - unattended-upgrades
    - uuconfig

- name: Apt-daily-upgrade timer override dir
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory
    mode: 0755
  when:
    uu_timer_oncalendar is defined or
    uu_timer_randomizeddelaysec is defined
  tags:
    - unattended-upgrades
    - timer

- name: Apt-daily-upgrade timer override
  ansible.builtin.template:
    src: apt-daily-upgrade.timer.override.conf.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    mode: 0644
  when:
    uu_timer_oncalendar is defined or
    uu_timer_randomizeddelaysec is defined
  notify:
    - Apt-daily-upgrade.timer restart
  tags:
    - unattended-upgrades
    - timer

- name: Remove apt-daily-upgrade timer override
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    state: absent
  when:
    not (
    uu_timer_oncalendar is defined or
    uu_timer_randomizeddelaysec is defined
    )
  tags:
    - unattended-upgrades
    - timer

- name: Remove apt-daily-upgrade timer override dir
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: absent
  when:
    not (
    uu_timer_oncalendar is defined or
    uu_timer_randomizeddelaysec is defined
    )
  notify:
    - Apt-daily-upgrade.timer restart
  tags:
    - unattended-upgrades
    - timer
