---
# handlers file for unattended-upgrades

- name: apt-daily-upgrade.timer restart
  systemd:
    name: apt-daily-upgrade.timer
    daemon_reload: yes
    state: restarted

- name: systemd reload
  systemd:
    daemon_reload: yes
